plugins {
    id 'java'
    id 'application'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(platform("software.amazon.awssdk:bom:2.27.21"))
    implementation "software.amazon.awssdk:polly:2.32.10"
    implementation("com.openai:openai-java:4.8.0")
    implementation 'software.amazon.awssdk:regions:2.22.26'
}

sourceCompatibility = '1.8'
targetCompatibility = '1.8'

application {
    mainClass = 'game.Main'
}
